### Listar produtos
GET http://localhost:3000/produtos

### Adicionar produtos
POST http://localhost:3000/produtos
content-type: application/json

{
    "nome": "Champignon",
    "preco": 15.99,
    "dataValidade": "2025-12-31",
    "quantidadeEstoque": 150
}

### Inserir produto novo
PUT http://localhost:3000/produtos/1
content-type: application/json

{
    "id": 1,
    "nome": "Teste",
    "preco": 170.00,
    "dataValidade": "2025-01-01",
    "quantidadeEstoque": 20
}

### Deletar produto
DELETE http://localhost:3000/produtos/1
content-type: application/json